### ISSUE TITLE
shortcuts are wrongly offset when using `gb` while workspace is in a detached state

### ISSUE THREAD

**Issue by dlee** [scmbreeze/scm_breeze#127]
This is in zsh:

```
❯ gb
* [1]  (detached from 2fb24c7)
  [2]  somebranch
```

The output seems correct, but the variables are incorrect:

```
❯ env
e1=(detached
e2=from
e3=2fb24c7)
e4=somebranch
```

**Comment by ilkka** [comment]
The same happens when one runs `gba`:

```
$ git clone https://github.com/github/linguist
Cloning into 'linguist'...
...
Checking connectivity... done.
$ cd linguist
$ gba
* [1]  master
  [2]  remotes/origin/HEAD -> origin/master
  [3]  remotes/origin/an-example-comparison-for-docs
  [4]  remotes/origin/bkeepers/gitattribute-docs
  [5]  remotes/origin/combine-gems
  [6]  remotes/origin/cut-release-v4.3.0
  [7]  remotes/origin/dont-allow-nested-extensions
  [8]  remotes/origin/emacs-vim-mode-lines
  [9]  remotes/origin/master
  [10] remotes/origin/more-relative-paths
  [11] remotes/origin/objc-mercury
  [12] remotes/origin/path-for-fileblob
  [13] remotes/origin/remove-script-ext
  [14] remotes/origin/revert-1976-path-for-fileblob
  [15] remotes/origin/revert-2014-revert-1976-path-for-fileblob
  [16] remotes/origin/rewrite-readme
  [17] remotes/origin/spew-mkmf
  [18] remotes/origin/strategies
  [19] remotes/origin/test/attributes
  [20] remotes/origin/text-html-ruby
  [21] remotes/origin/use-all-ext-segments
  [22] remotes/origin/vendor-grammar-sources
  [23] remotes/origin/vmg/2
  [24] remotes/origin/vmg/lol-pygments
  [25] remotes/origin/vmg/new-languages
  [26] remotes/origin/vmg/rugged-22b3
  [27] remotes/origin/vmg/tmscopes
$ echo $e3
->
```

So it just seems to tokenize whatever is on the lines, breaking at every space.

**Comment by ghthor** [comment]
Hmm, this is an interesting bug. I feel like a quick fix would be to remove the HEAD branch of remotes from the output.

**Comment by vise890** [comment]
What's the motivation for tokenizing on space rather than newline?

**Comment by ghthor** [comment]
`[2]  remotes/origin/HEAD -> origin/master` <- This line fucks everything up.

```
$e2=remotes/origin/HEAD
$e3=->
$e4=origin/master
```

**Comment by ghthor** [comment]
`$e2="remotes/origin/HEAD -> origin/master"` doesn't really fix anything either.

**Comment by vise890** [comment]
ok, what about split on `EOL`s, then strip everything in each element after the first space

**Comment by vise890** [comment]
```git branch -a | split "\n" | map "split \"\\s\" | first "```

**Comment by ghthor** [comment]
Ok, that handles the HEAD case, but what about the first case in this PR

```
❯ gb
* [1]  (detached from 2fb24c7)
  [2]  somebranch
```

The, first word solution, would leave `$e1=(detached`. =/

**Comment by vise890** [comment]
ok but we're making progress. at least it won't offset everything else.

so my git (2.11.1) gives this output when in a detached head state:
```
* (HEAD detached at 453f40c)
  master
```
i propose this new algorithm in pseudo-bash then:

```bash
function first_word {
  echo $1 | split "\s" | first
}
function is_detached_head {
  echo $1 | matches "\([\w\s]+\)$"
}
function branch_ref {
  if [ is_detached_head $1 ]; then
    echo "HEAD"
  else
    first_word $1
  fi
}
git branch -a | split "\n" | map branch_ref
```

**Comment by ghthor** [comment]
That works and we've fixed broken functionality; But we lose information in the UI.

```
$> gba-old
* [1] (HEAD detached at b1a6ae6)
  [2] master
  [3] remotes/origin/HEAD -> origin/master
  [4] remotes/origin/master
$> gb-new
* [1] HEAD
  [2] master
  [3] remotes/origin/HEAD
  [4] remotes/origin/master
```
We now has lost indication that we're in a detached head pointing at b1a6ae6, and we've also lost that remotes/origin/HEAD points to origin/master. After thinking about this, I think the UI should be as informative as possible, even if that means that executing `gco 3` isn't functional. That is a separate issue.

Considering that, we should split on newlines as this commit is doing.

**Comment by ghthor** [comment]
Just to clarify. I'd like to add support to git checkout for strings such as `(HEAD detached at b1a6ae6)` and `remotes/origin/HEAD -> origin/master` to just do the right thing.

**Comment by vise890** [comment]
so .. the number you show in `[]` can be done by splitting on new lines; the values of the `eX` env vars can be done with the fancier algo

**Comment by ghthor** [comment]
Yes, you are right! It didn't even dawn on me, but I was reading through
that code thinking, we call git branch twice, shouldn't we be caching that
value...? :thumbsup: You want to move forward with it or shall I?

**Comment by vise890** [comment]
can we just re-open this issue for now? it's a bit meatier than other stuff and i feel a bit uncomf moving forward without having some really kickass testing  and travis

**Comment by ghthor** [comment]
Sure, that's fine. Sorry for moving forward with merging before waiting for
your response.
