### ISSUE TITLE
Doesn't seem to work in zsh

### ISSUE THREAD

**Issue by jkwiecien** [scmbreeze/scm_breeze#158]
This is really weird as I use this on my other Mac with the same config, and it works there.

I'm using zsh. Installation completes and I can see all the files under ~/.scm_breeze. 

Line was added to my .zshrc
# SCM Breeze

[ -s "/Users/jacek/.scm_breeze/scm_breeze.sh" ] && source "/Users/jacek/.scm_breeze/scm_breeze.sh"

This path is correct, I did source zshrc... still aliases doesn't work

**Comment by LM450N** [comment]
This issue is fairly old and there hasn't been much activity on it. ⌛

**Comment by ghthor** [comment]
I have no idea what the state of zsh support is. I've only been using bash for the last few years. May just remove references to the zsh support and leave it hidden until someone finds it and wants to maintain it.

**Comment by g5pw** [comment]
I use `scm_breeze` on ZSH, no problems at all!

**Comment by ghthor** [comment]
@g5pw That's awesome, do you have to patch anything?

**Comment by ghthor** [comment]
The zsh tests are passing on linux and osx now. I'm going to close this considering your feedback!
