### ISSUE TITLE
Support for fish shell

### ISSUE THREAD

**Issue by edutrul** [scmbreeze/scm_breeze#181]
Would be awesome that works also with fish shell
fishshell.com

"so far all commands are not found with fish"

Thanks

**Comment by ghthor** [comment]
I'll be looking into adding support for this soon.

**Comment by kholbekj** [comment]
@ghthor Did this stall? Is there anything can be done to help?

**Comment by ghthor** [comment]
I haven't ever used the fish shell. Does scmpuff support the fish shell? I'd recommend using scmpuff if it does.

Otherwise we're going to need an effort from fish shell wizards to bring support.

**Comment by shinriyo** [comment]
thank you I change scmpuff

**Comment by shinriyo** [comment]
@ghthor it can't work in fish shell. so, finally I stated to develop.
https://github.com/shinriyo/breeze

**Comment by ghthor** [comment]
@shinriyo Thanks! Put a link to your project in our README.

**Comment by edutrul** [comment]
Thanks @shinriyo
