### ISSUE TITLE
my short cut request

### ISSUE THREAD

**Issue by shinriyo** [scmbreeze/scm_breeze#182]
git update-index --skip-worktree hoge
git update-index --no-skip-worktree hoge
git open (like this https://github.com/paulirish/git-open)

or could you tell me how to add to your source cooe?
I will fix and create pull request.

**Comment by michaelmior** [comment]
You can easily add your own shortcuts in your shell init script. If you want to try for PR, you'll need to change the [aliases file](https://github.com/ndbroadbent/scm_breeze/blob/master/lib/git/aliases.sh).

**Comment by ghthor** [comment]
Still open to having these in a PR. Thanks for sticking around if you're still a user.
