### ISSUE TITLE
Breaks cd when using other languages

### ISSUE THREAD

**Issue by onilton** [scmbreeze/scm_breeze#183]
I am using ubuntu 14.04 (in portuguese).

After install scm_breeze and sourcing it in my .bashrc, when I try to change to a dir I get:

```
user@mycomputer:~$ cd tdc/
bash: tdc/: É um diretório
```

(tdc: Is a directory)

When I change my system settings to use english, everything seems to work fine.

Running this cd in `bash -X`, i get:

```
user@mycomputer:~$ cd tdc/
+ exec_scmb_expand_args tdc/
++ scmb_expand_args tdc/
++ '[' tdc/ = --relative ']'
++ first=1
++ OLDIFS='     
'
++ IFS=' '
++ for arg in '"$@"'
++ [[ tdc/ =~ ^[0-9]{0,4}$ ]]
++ [[ tdc/ =~ ^[0-9]+-[0-9]+$ ]]
++ '[' 1 -eq 1 ']'
++ first=0
++ printf %s tdc/
++ IFS='    
'
++ sed -e 's/\([][|;()<>^ "'\'']\)/\\\1/g'
+ eval tdc/
++ tdc/
bash: tdc/: É um diretório
++ history -a
```

I am using the stock settings of scm_breeze, also I reset my .bashrc to stock settings.

**Comment by onilton** [comment]
Removing `cd` from the list of commands in `.git.scmbrc`, seems to "fix" the issue:

```
# Shell Command Wrapping
# ----------------------------------------------
# Expand numbered args for common shell commands
shell_command_wrapping_enabled="true"
# Here you can tweak the list of wrapped commands.
#scmb_wrapped_shell_commands="vim emacs gedit cat rm cp mv ln cd" # broken
scmb_wrapped_shell_commands="vim emacs gedit cat rm cp mv ln" # working
# Add numbered shortcuts to output of ls -l, just like 'git status'
```
This seems a regression from bugs #98 and #64

**Comment by ghthor** [comment]
@HaleTom Will your #255 fixes help here?

**Comment by HaleTom** [comment]
@ghthor I hope so...

@onilton can you show how to:

1. Set language to English
1. That it works
1. Set another language
1. That it now fails
