### ISSUE TITLE
Why is git checkout -b gcb and not gcob?

### ISSUE THREAD

**Issue by ryanseys** [scmbreeze/scm_breeze#184]
`gc` is `git commit`
`gco` is `git checkout`
so `gcob` should be `git checkout -b` ?

**Comment by LM450N** [comment]
I think `git checkout` is `gco` because `gc` was already took by `git commit`. But for `git checkout -b`, the `gcb` alias was available and it's one letter less than `gcob`.

**Comment by robwise** [comment]
I dunno, I agree with @ryanseys, `gcob` is more intuitive given `gco` is git commit

**Comment by LM450N** [comment]
This issue is fairly old and there hasn't been much activity on it. ⌛

**Comment by Ghostavio** [comment]
`alias gcob="gcb "` and 💥

**Comment by ghthor** [comment]
This is easy enough to change on a individual level. I sort of agree, but I'm not going to change a default alias like this without serious consensus from all users.
