### ISSUE TITLE
fatal: Command not found

### ISSUE THREAD

**Issue by sblask** [scmbreeze/scm_breeze#190]
I am getting a `fatal: Command not found` after every command and none of the scm breeze functionality works using scm_breeze with zsh because of https://github.com/ndbroadbent/scm_breeze/pull/150

I do have hub and I do have gh:

$ which hub
/home/sebastian/.bin/hub

$ which gh
/usr/bin/gh

Not sure where exactly the error comes from.

As `gh` is now `hub`, should the check for `gh` not be removed? Or at least the order be changed?

**Comment by sblask** [comment]
Not sure why it's installed, but it's a node module:

ls -lha /usr/bin/gh
lrwxrwxrwx 1 root root 32 Sep  2 16:50 /usr/bin/gh -> ../lib/node_modules/gh/bin/gh.js

**Comment by gregpearce** [comment]
If anyone is currently having this error, I just started having it for a totally different reason. If you are an oh-my-zsh user, check that the line `plugins=(___, ___)` in your .zshrc file does NOT contain git. The oh-my-zsh git plugin does it's own versions of the same aliases as scm_breeze which now breaks it (for some reason wasn't breaking it for me in previous versions).

**Comment by ndbroadbent** [comment]
Hi, I've just pushed an update that removes the "gh" check. I just found out that oh-my-zsh is now including it's own `gh` alias for `git help`. Should be fixed now.
