### ISSUE TITLE
scm_breeze broken after update?

### ISSUE THREAD

**Issue by tirithen** [scmbreeze/scm_breeze#209]
Hi, suddenly today after upgrading scm_breeze both running git with and without the aliases seem broken. :/ If I uninstall scm_breeze. 

    ➜  clinical-models git:(master) ✗ gpl
    git:10: command not found: gh
    ➜  clinical-models git:(master) ✗ gp
    git:10: command not found: gh
    ➜  clinical-models git:(master) ✗ git pull
    git:10: command not found: gh
    ➜  clinical-models git:(master) ✗ git push
    git:10: command not found: gh

**Comment by tirithen** [comment]
I realized that it might be related to oh-my-zsh update, I tend to mix them up some times but still the aliases are broken. :/

**Comment by LM450N** [comment]
Ok, I confirm. I've just update `oh-my-zsh` and my aliases are broken. 🔨  Damn... 😑

**Comment by fbvilela** [comment]
removing that line worked for me too. Thanks for the catch, @LM450N !

**Comment by tirithen** [comment]
Thanks @LM450N ! So happy that I can use scm_breeze again. :D My muscle memory kept trying to type the shortenings instead of git status/diff/commit and so on.

**Comment by ndbroadbent** [comment]
Hi, this is strange. Can someone please post the output of `type gh`?

**Comment by ndbroadbent** [comment]
I pushed an update to comment out this line, but would like to figure out why it's happening

**Comment by tirithen** [comment]
I have the line commented out and get the following (I have not spent time understanding the reason of the issue)

    $ type gh
    gh is an alias for git help

**Comment by ndbroadbent** [comment]
Ohhhhh I see. I think oh-my-zsh is including it's own git aliases then. `gh` was initially a command-line tool for GitHub before it was merged into `hub`. So I don't think we need to worry about that anymore

**Comment by LM450N** [comment]
You're welcome guys! 😉
