### ISSUE TITLE
`ls` directory content command not working anymore

### ISSUE THREAD

**Issue by iacobson** [scmbreeze/scm_breeze#212]
when running the `ls` command to see the directory content, I get the following error:
`fatal: Not a git repository (or any of the parent directories): .git`

if I run `source ~/.zshrc` in the terminal / iterm2, this gets fixed,
but then, each new terminal tab, will have the same issue.

I'm using `zsh` with `ohmyzsh`
I think this issue started after the last update of `ohmyzsh`

Uninstalling completely the scm_breeze solves the issue, while installing it again brings back the same behaviour. 

Please let me know if you need any more info

Update: when I am in a git repository, same `ls` command outputs `error: option 'color' expects "always", "auto", or "never"`

**Comment by gaiottino** [comment]
I've gotten the same issue. Very annoying.

**Comment by mcocapiza** [comment]
I had the same wrong behavior yesterday...I think I did a "brew update" by mistake and then discovered the "ls" didn't work anymore.
By now and waiting for a fix, I commented the next line into the "~/.zshrc" file:

#[ -s "/Users/mcocapiza/.scm_breeze/scm_breeze.sh" ] && source "/Users/mcocapiza/.scm_breeze/scm_breeze.sh"

Hope this is useful for you.

**Comment by iacobson** [comment]
@mcocapiza I think that disables the scm_breeze, which I wouldn't want to...
I will try to disable some of the scm_breeze modules and leave only the git shortcuts, to see if that fixes anything

**Comment by ndbroadbent** [comment]
Sorry about that. I don't have much time to look into this and try to reproduce it, but it would be great if someone could figure this out and submit a pull request.

In the meantime you can add `export shell_ls_aliases_enabled="false"` to `~/.zshrc`, which disables the "ls" aliases.

**Comment by iacobson** [comment]
@ndbroadbent thank you. Unfortunately I tried to add the export `shell_ls_aliases_enabled="false"` to .zshrc but still getting the same issue :/
Tried both in iTerm and Terminal

**Comment by iacobson** [comment]
@ndbroadbent 
Update: after trying the above, I tried to move the 
` [ -s "$HOME/.scm_breeze/scm_breeze.sh" ] && source "$HOME/.scm_breeze/scm_breeze.sh" `
above 
` source $ZSH/oh-my-zsh.sh` 
in the `.zshrc`

This way `ls` works without manually running `source ~/.zshrc`

But this time I get this error each time i start a terminal:
`/Users/dorianiacobescu/.scm_breeze/lib/git/aliases.sh:190: command not found: compdef`

**Comment by baumhoto** [comment]
seems to be related to the `git_log_stat_alias` . if you go to your `~/.git.scmbrc` and change the alias from `gls`  to something else e.g. `glsa` then it works again. `git_log_stat_alias="glsa"`
Maybe someone can verify this?

**Comment by gaiottino** [comment]
@baumhoto that seems to have solved the issue. Thanks.

**Comment by iacobson** [comment]
@baumhoto it works, thanks!
