### ISSUE TITLE
Homebrew

### ISSUE THREAD

**Issue by chrisfinazzo** [scmbreeze/scm_breeze#222]
If this is still being maintained, I would like to package it for Homebrew. Can someone please put a version number on this so that Homebrew can pull it?

**Comment by MichaelDimmitt** [comment]
@chrisfinazzo, looks like they have posted a release v1.0.0 in 2012.

**Comment by ghthor** [comment]
Yeah, this has been on my TODO list for far too long, to cut a new release. I don't feel like the current state of the project is ready to be a brew package, I can mark a new release at any rate to support this is need be. I'm Looking for guidance from any current users that might be active here.

**Comment by chrisfinazzo** [comment]
@ghthor I have a version of `uninstall.sh` that fleshes out this command a bit more - separate paths for GNU and Darwin, that sort of thing. I haven't touched it in a while though I'd need to refresh my memory about where things were when I left it. My thinking was that this could be a 1.1 or something like that.

Nothing urgent, it just seemed like a useful tool that would be easy for Homebrew to pick up and being mostly shell, it was not that difficult to wrap my head around what it's supposed to do.

Closing this for now...

**Comment by ghthor** [comment]
@chrisfinazzo That's great. When you submit a PR I'll pull and mark a new release for 1.1 so we can pack this up in Homebrew! Thanks for your patience and the work you've done
