### ISSUE TITLE
README is very verbose

### ISSUE THREAD

**Issue by vise890** [scmbreeze/scm_breeze#224]
Installation instructions are at the bottom, after a bunch of other stuff that I have never actually read.

IMO, it should be somehting like:
* logo! ( 😄 )
* brief description
* table of contents
* install instructions
* usage (cheatsheet!)
* the other stuff

some examples that I find more legible are:
* [https://github.com/sindresorhus/pageres](https://github.com/sindresorhus/pageres)
* [https://github.com/rstacruz/hicat](https://github.com/rstacruz/hicat)

**Comment by ghthor** [comment]
Prune it!

**Comment by vise890** [comment]
I had a first stab at this in #225

**Comment by vise890** [comment]
should we close this? I feel it'll be ok, especially after we take out the stuff on the design directory and the repo index as per #220

**Comment by jeffbyrnes** [comment]
@vise890 yeah, I think we can organically tackle this as we clean up this repo.
