### ISSUE TITLE
start travis builds

### ISSUE THREAD

**Issue by vise890** [scmbreeze/scm_breeze#226]
I've updated the travis link to point to this repo in #225.

Someone with access to the organization should create that pipeline on travis.

**Comment by ghthor** [comment]
I'll take a look at this sometime this week, I haven't ever done anything with travis before so I'll have to read some documentation if it isn't immediately straightforward.

**Comment by jeffbyrnes** [comment]
Happy to help; I use Travis daily (if not hourly).

**Comment by vise890** [comment]
This should be super straightforward. The project is already configured. You just need to go to Travis and create the build, but someone with access to the github repo needs to do it.

**Comment by vise890** [comment]
they are alive!
