### ISSUE TITLE
Help with Maintenance

### ISSUE THREAD

**Issue by brb3** [scmbreeze/scm_breeze#238]
Hey @ndbroadbent -- it seems that this repository is starting to show its age.

I would be very interested in helping with maintenance. It seems that there are 2 or 3 PRs that are ready to merge, and another 2 (at least) that need minor work to get merged in.

If you'd like help, please let me know. I use this project daily, and would hate to see developers lose interest.

**Comment by ghthor** [comment]
@brb3 ndbroadbent doesn't maintain the project anymore. I'd love your help! Don't hesitate to dig in, do that minor work or point me to the PR's that are ready to merge. ^-^

**Comment by brb3** [comment]
@ghthor Understood. I'll dig in this afternoon.

**Comment by wcpines** [comment]
This issue can probably be closed, yes? :P
