### ISSUE TITLE
shell commands don't work

### ISSUE THREAD

**Issue by lifehackett** [scmbreeze/scm_breeze#239]
Hi, love this lib so thank you for creating it. I have used it for a while, though was on an older version. I don't recall the shell aliases being there before, but perhaps they were always there working seamlessly.  

My setup
`zsh`
`prezto`
`tmux`

(Note: running inside a tmux session vs not did not make a difference)

After installing `scm_breeze` on a new laptop shell commands stopped working and took several seconds to complete. Specifically `cp` and `rm`. I would `rm` a file. It would "work" for a few seconds and then appear to complete, but the file would still be there. Same for `cp`

I tried turning it off in `.git.scmbrc` with `shell_command_wrapping_enabled="false"` but that did not solve the issue. For now I have uninstalled `scm_breeze` and everything is working again. Do you have any other ideas for resolving the issue?

**UPDATE**
15 inch Macbook Pro 2017
OSX Sierra (10.12.6)
2.9 GHz Intel Core i7

**Comment by MichaelDimmitt** [comment]
@lifehackett, any additional details about your environment would be helpful for recreating the issue, Operating System? Current OS Version/Update? Hardware Specifications.

**Comment by lifehackett** [comment]
@MichaelDimmitt original post updated with that info (to keep it consolidated)

**Comment by lifehackett** [comment]
@MichaelDimmitt Did a fresh install and turned off shell commands and it seems to be working. Not sure what the difference is as I both sourced `~/.zshrc` and restarted iTerm last time after making the config update. 

Anyhow, wanted to post the update and will close the issue.
