### ISSUE TITLE
Cannot determine sed extended regex argument with `set -o pipefail`

### ISSUE THREAD

**Issue by HaleTom** [scmbreeze/scm_breeze#250]
```
% set -o pipefail
% source shell_shortcuts.sh 
Cannot determine extended regex argument for sed! (Doesn't respond to either -E or -r)
```

I'm running `sed` version:

```
% sed --version | head -n1
sed (GNU sed) 4.5
```

**Comment by ghthor** [comment]
Looks like these tests[1] fail their job if `pipefail` is activated. Don't know what exactly to do about it =/

[1] https://github.com/scmbreeze/scm_breeze/blob/master/lib/git/shell_shortcuts.sh#L13
