### ISSUE TITLE
Ctrl + x + space is now giving me: " git_commit_all^M"

### ISSUE THREAD

**Issue by ndbroadbent** [scmbreeze/scm_breeze#261]
I just pulled the latest scm_breeze, and the Ctrl + x + space shortcut is now giving me " git_commit_all^M" in the terminal, instead of simulating the enter key. (Using bash.)

Was wondering if something has changed that would affect that?

**Comment by ndbroadbent** [comment]
Ah looks like this was in 1f3b8a6b11ab1d60cdbdea56525b4aefee8326a5

**Comment by ndbroadbent** [comment]
Related to PR: #246

**Comment by ghthor** [comment]
Sorry about this. I did poor dogfooding on that change because I don't use it. We should revert it until we figure out a better way to support #246's needs
