### ISSUE TITLE
Upgrade Travis CI environment to newer versions of bash and zsh

### ISSUE THREAD

**Issue by HaleTom** [scmbreeze/scm_breeze#264]
As can be seen in [this Travis CI output](https://travis-ci.org/scmbreeze/scm_breeze/builds/423527503?utm_source=github_status&utm_medium=notification) for PR #263: "Fix #167, #202, #204 and a bunch of other goodies", the tests only pass on zsh on MacOS.

However, all tests pass on my Manjaro Linux box.

In [Minimum bash and zsh version requirements #260](https://github.com/scmbreeze/scm_breeze/issues/260) I asked about which versions of `{ba,z}sh` this project requires as a pre-requisite, and the answer was:

> TL:DR; Use modern features, especially if they improve security and safety.

Given this, can the shells in Travis CI be upgraded?

**Comment by ghthor** [comment]
Alright, can you point me to all the places in #263 that require a modern bash shell? I'd just like to investigate what can be done to support a legacy bash shell. Please don't hate me =( I really appreciate all the work you've put into this and you've reinvigorated me concerning the upkeep of this project.

**Comment by ghthor** [comment]
Are there any projects that provide polyfills for shell support that we could incorporate? ala the javascript ecosystem.

**Comment by ghthor** [comment]
If not, I'd be interested in starting a shell polyfill project to provide support like this.

**Comment by HaleTom** [comment]
@ghthor see 48302bc and 80ec1ad for version work-arounds.

No need to upgrade yet: #260 agrees with the Linux Travis CI environment currently selected: Trusty Tahr 14.04.

I'd suggest an upgrade to Ubuntu 16.04 after 14.04 support ends April 2019.
