### ISSUE TITLE
gb doesn't work with no arguments

### ISSUE THREAD

**Issue by Alkaar** [scmbreeze/scm_breeze#277]
I tried to rule out other stuff in my .bash_profile and it seems when I add in scm breeze, git branch gives me the following error whether I use `gb` or `git branch`

$ gb
fatal: '' is not a valid branch name.
$

If I remove it and do a normal `git branch` it behaves fine

**Comment by mannyatico** [comment]
I have the same issue, and I'm using:

MacOS Mojave 10.14
zsh with prezto

**Comment by tuxinaut** [comment]
It broke for me after updating to the latest version, tracked it down to **PR** #263 - Fix #167, #202, #204, #274 and a bunch of other goodies
