### ISSUE TITLE
URL in the repository summary leads to 404

### ISSUE THREAD

**Issue by p-himik** [scmbreeze/scm_breeze#285]
Current URL is http://madebynathan.com/2011/10/18/git-shortcuts-like-youve-never-seen-before/
If you follow it, it'll say: "Uh oh! Page not found!"

**Comment by jeffbyrnes** [comment]
Looks like an “off by one” error, this URL works: https://madebynathan.com/2011/10/19/git-shortcuts-like-youve-never-seen-before/

**Comment by ghthor** [comment]
Dope! Thanks for the headsup, should be fixed now =)
