### ISSUE TITLE
scm_breeze added to Arch User Repository

### ISSUE THREAD

**Issue by ilai-deutel** [scmbreeze/scm_breeze#291]
Hi,

Firstly, thank you for these useful scripts! I have added SCM Breeze to the AUR (Arch Linux user package repository). The new package is available [here](https://aur.archlinux.org/packages/scm_breeze-git/).

The scripts and libraries are available system-wide in `/usr/share/scm_breeze` and `/usr/lib/scm_breeze`, but each user who wishes to use scm_breeze has to run `install-scm-breeze` (which corresponds to `install.sh`) to create `~/.git.scmbrc`. If #235 is fixed, running the installation script will become optional.

Let me know if you have suggestions, questions or comments.

**Comment by ghthor** [comment]
This is great, thanks for adding this into the AUR =)
