### ISSUE TITLE
Getting an error when using `gb` shortcut.

### ISSUE THREAD

**Issue by ryanhinton** [scmbreeze/scm_breeze#293]
Hello, this is probably another bug for Windows users.
Whenever I attempt to execute `gb`  shortcut for `git branch`, I get the following error.

```
λ gb
bash: /c/Program: No such file or directory
<< was unexpected at this time.
```
Is there something I need to do with configuration files or is this a problem somewhere in the code by chance?  I'm not sure why some shortcuts work and some do not.

Thank you for any feedback.

**Comment by ryanhinton** [comment]
Hmmm.... I'm now thinking this issue has nothing to do with SCM Breeze since even `git branch` produces the same error.

**Comment by ghthor** [comment]
Scm breeze sets a shell function for the value of `git`.

```
$ type git
git is a function
git () 
{ 
    case $1 in 
        commit | blame | add | log | rebase | merge | difftool)
            exec_scmb_expand_args "$_git_cmd" "$@"
        ;;
        checkout | diff | rm | reset)
            exec_scmb_expand_args --relative "$_git_cmd" "$@"
        ;;
        branch)
            _scmb_git_branch_shortcuts "${@:2}"
        ;;
        *)
            "$_git_cmd" "$@"
        ;;
    esac
}
$ which git
/usr/bin/git
```

Try`$(which git) branch` and see if the error goes away.

**Comment by ghthor** [comment]
This looks like the `git branch` support is messing up on windows.

**Comment by ryanhinton** [comment]
Thank you for your reply :-) I tried your recommendation, but receive the same error.
```
λ $(which git) branch
bash: /c/Program: No such file or directory
```

**Comment by ghthor** [comment]
Ok, so what type of bash environment are you using on windows? Looks like
there is a path with a space `/c/Program Files/..` that isn't being handled
correctly.

**Comment by ghthor** [comment]
What is the output of `which git`

**Comment by ryanhinton** [comment]
```
λ which git
/c/Program Files/Git/bin/git
```

**Comment by ghthor** [comment]
Yep, that path with the space is messing this up. I don't know how to handle this to be honest, I'll have to look into this further. The error you are getting is likely coming from [here](https://github.com/scmbreeze/scm_breeze/blob/master/lib/git/branch_shortcuts.sh#L18). But anywhere with [_git_cmd](https://github.com/scmbreeze/scm_breeze/search?q=_git_cmd&unscoped_q=_git_cmd) would need to be audited to ensure it supports path to executable with a space.

**Comment by ghthor** [comment]
The quick fix would be to reinstall your to a filepath without a space.

**Comment by ryanhinton** [comment]
is that a part of SCM Breeze or Git itself?

**Comment by ryanhinton** [comment]
I think I'm able to trail through this.  Let me see if I can fix it and possibly be able to make a PR, if that is possible?

**Comment by ghthor** [comment]
The function [bin_path](https://github.com/scmbreeze/scm_breeze/blob/7152788516bd360e705d229810075c0cdb031c33/lib/git/helpers.sh#L21) is what is returning the path with a space in it. We'd need to do some type of additional processing on the path there to make it support paths with spaces. =/

**Comment by ryanhinton** [comment]
FYI, I did try to make this work, but kept receiving various areas.  I'm rather new to shell scripting.  I thought it would be simply a search and replace to escape spaces with a backslash and space, but with limited time and knowledge, I could not make it work.  Instead, I uninstalled Git and installed it to the C:\ root path rather than C:\Program Files.  This allowed `gb` to work.
