### ISSUE TITLE
ASYNC_PTYS[]: invalid parameter name

### ISSUE THREAD

**Issue by dzlab** [scmbreeze/scm_breeze#305]
I've installed scm_breeze and now for any git command i keep getting the same error

```
➜ repo (feature/1) ✗ git status
# On branch: feature/1  |  [*] => $e*
#
➤ Changes not staged for commit
#
#       modified: [1] file1.scala 
#       modified: [2] file2.scala 
#       modified: [3] file3.scala 
#
➜  repo (feature/1) ✗ zle -F 11 _async_zle_watcher
➜  repo (feature/1) ✗ 
async_stop_worker:unset:9: ASYNC_PTYS[]: invalid parameter name
```
I'm on macOS Catalina 10.15.6 and using Oh My Zsh

I'm not sure who is trying to do the `zle -F 11 _async_zle_watcher`, I looked into scm_breeze and couldn't find any reference to this command. Any hints how I could fix this?

**Comment by dzlab** [comment]
It turns out the problem was cased by this line in `~/.zshrc`
```
[ -s "/Users/dzlab/.scm_breeze/scm_breeze.sh" ] && source "/Users/dzlab/.scm_breeze/scm_breeze.sh"
```
Removing the first part and keeping the source part fixed the problem
```
source "/Users/dzlab/.scm_breeze/scm_breeze.sh"
```

**Comment by ghthor** [comment]
That's a very strange problem, I'm glad that you got it fixed. zsh must be doing something unexpected for a pattern as common as `check if source file exists && source the file` to break.
