### ISSUE TITLE
Bash completion doesn't work for git v2.30

### ISSUE THREAD

**Issue by telzhov** [scmbreeze/scm_breeze#306]
Happy New Year everyone!
Upgraded git to v2.30, typed in bash command line 'g', \<space\>, \<tab\>, and got:
```
$ g bash: completion: function `_git' not found
$ g 
```
Checked /usr/share/bash-completion/completions/git, and yes, there is no '_git' function defined there (it's there for git <= v2.29.x). So it would be nice for SCM breeze to support v2.30 as well :)

Thanks a lot for your efforts!

**Comment by ghthor** [comment]
Well, since you have the environment setup already, do you think you could
hack at it and submit a patch that can support git 2.30. They must have
renamed the completion function, or maybe someone packaged 2.30
incorrectly.

**Comment by indexless** [comment]
Thanks, done #307

**Comment by indexless** [comment]
Accidentally closed, reopening.
