### ISSUE TITLE
File.exists? is deprecated in ruby 3.2.0

### ISSUE THREAD

**Issue by neocoin** [scmbreeze/scm_breeze#322]
https://github.com/scmbreeze/scm_breeze/blob/0e21e89f3a32c9967f84a3b2ace761544094e9de/lib/git/status_shortcuts.rb#L91

Plz change to `File.exit?`

ref https://bugs.ruby-lang.org/issues/17391

**Comment by ghthor** [comment]
Alright, I’ll see what I can do about this.

**Comment by rodolfoggp** [comment]
I'm having the same problem here

**Comment by jennifersarahpaul** [comment]
I'm having this issue as well. I tried to run `update_scm_breeze` to get this fix and I just get 
```
fatal: unable to connect to github.com:
github.com[0: 140.82.114.3]: errno=Operation timed out
```
