### ISSUE TITLE
sudo: exec_scmb_expand_args: command not found 

### ISSUE THREAD

**Issue by jpablobr** [scmbreeze/scm_breeze#69]
Hi, 

I did a upgrade and now I'm getting the following when I run `sudo somthing` 

``` sh
sudo: exec_scmb_expand_args: command not found
```

**Comment by essmahr** [comment]
+1 also seeing this issue, with zsh. Have tried all of the above with a root `.zshrc` and `.profile` and still getting this error. OS 10.11.6, zsh 5.2.
