### ISSUE TITLE
support for fish shell

### ISSUE THREAD

**Issue by delor** [scmbreeze/scm_breeze#92]
http://fishshell.com/
fish is a smart and user-friendly command line shell for OS X, Linux, and the rest of the family

**Comment by khronnuz** [comment]
@ndbroadbent my suggestion would be to leave this one open so people don't keep opening new ones and can understand why it is not working. This is also a good mark to people know it is not supported and be inspired to create a pull request.

e.g. https://github.com/ndbroadbent/scm_breeze/issues/181
